### ISSUE TITLE
Multi Arch Image Inquiry

### ISSUE THREAD

**Issue by stephenjdawson** [bitnami/bitnami-docker-node-exporter#6]
Description
bitnami-docker-node-exporter does not seem to be multi-arch, and therefore does not deploy on RPI's or other arm devices. 

**Steps to reproduce the issue:**

1. Have a cluster with Arm machines (mine has amd64 and arm).
2. Use Bitnami Kube-Prometheus Helm Chart 0.53.1 to create a release.  
3. Inspect relevant pods

**Describe the results you received:**

CrashLoop backoff

**Describe the results you expected:**

pods run on arm

**Additional information you deem important (e.g. issue happens only occasionally):**

I am considering forking / pulling this repo in with git subtree to try to update to use image index and manifests to be able to deploy on both arm and amd64 in my hybrid cluster. I have not done this before so I am wondering if it has been tried/ if it is worth an attempt?

**Comment by carrodher** [comment]
Hi all, we just created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
